services:
  api:
    ports:
      - "8000:8000"
    build: ./api
    volumes: ["./api:/app"]
    depends_on:
      - db
  db:
    restart: always
    build: ./db/
    environment:
      MYSQL_DATABASE: "FinderDB"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"