services:
  api:
    build: ./api/
    command: sh -c "python3 api.py"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    build: ./db/
    environment:
      MYSQL_DATABASE: "FinderDB"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
