services:
  pythonapp:
    build: ./app/
    command: sh -c "sleep 10s ; python3 test.py"
    depends_on:
      - mysql

  mysql:
    restart: always
    build: ./mysql/
    environment:
      MYSQL_DATABASE: "FinderDB"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
